"""Extract :root { ... } and .light { ... } from the Insert Coin design system HTML
and write a curated tokens.css for the print/EPUB pipeline.

Usage:
    python -m heinlein.scripts.sync_design_tokens [--source PATH]
"""
from __future__ import annotations

import argparse
import re
from pathlib import Path

DEFAULT_SOURCE = Path("/tmp/insert_coin_template.html")
TARGET = Path(__file__).resolve().parents[1] / "templates" / "tokens.css"

# We keep only the variables the print/EPUB stylesheets consume.
ALLOWLIST = {
    "--paper", "--ink", "--ink-muted", "--rule",
    "--neon-pink", "--accent", "--gold",
    "--bg-deep", "--fg-dark", "--fg-dark-muted",
    "--neon-pink-d", "--accent-d", "--gold-d",
}


def _extract_block(html: str, selector: str) -> dict[str, str]:
    """Pull `selector { ... }` and return {prop: value}."""
    pattern = re.compile(
        re.escape(selector) + r"\s*\{([^}]*)\}", re.DOTALL,
    )
    m = pattern.search(html)
    if not m:
        raise SystemExit(f"could not find `{selector} {{}}` block")
    body = m.group(1)
    props: dict[str, str] = {}
    for line in body.splitlines():
        line = line.split("/*", 1)[0].strip().rstrip(";")
        if not line or ":" not in line:
            continue
        k, v = line.split(":", 1)
        props[k.strip()] = v.strip()
    return props


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--source", type=Path, default=DEFAULT_SOURCE)
    ap.add_argument("--out", type=Path, default=TARGET)
    args = ap.parse_args(argv)

    html = args.source.read_text(encoding="utf-8")
    # Print uses the .light variant for ink-on-paper colours, plus dark
    # foundations from :root for the cover and end pages.
    root = _extract_block(html, ":root")
    light = _extract_block(html, ".light")

    merged = {k: light.get(k, root.get(k)) for k in ALLOWLIST}
    # Carry through dark-page neons explicitly from :root (override light's lighter set
    # only where the print spec cares).
    for k in ("--bg-deep", "--neon-pink-d", "--accent-d", "--gold-d", "--fg-dark", "--fg-dark-muted"):
        if root.get(k):
            merged[k] = root[k]

    # Some tokens aren't in the design system source but the print pipeline expects:
    # synthesise ink-muted / rule from light.
    if not merged.get("--ink-muted") and light.get("--fg-muted"):
        merged["--ink-muted"] = light["--fg-muted"]
    if not merged.get("--rule") and light.get("--border"):
        merged["--rule"] = light["--border"]

    lines = [
        "/* Insert Coin design tokens — print/EPUB subset.",
        "   Auto-generated by heinlein.scripts.sync_design_tokens. Do not edit by hand. */",
        ":root {",
    ]
    width = max(len(k) for k in merged) + 1
    for k, v in merged.items():
        if v is None:
            continue
        lines.append(f"  {k}:{' ' * (width - len(k))}{v};")
    lines.append("}")

    args.out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
